#!/bin/bash
# clang options
# -I. search current directory for source files
# -g debugging info
# -c compile but not link. output is object code
# -o outputfile

clang -I. -g -Wall -c register.c
clang -I. -g -Wall -c alu.c
clang -I. -g -Wall -c alu-main.c
clang -I. -g -Wall -c test.c
clang -g -Wall -o alu register.o alu.o alu-main.o 
clang -g -Wall -o test-alu register.o alu.o test.o -lm
